### ISSUE TITLE
i am getting an error about photo_view: 

### ISSUE THREAD

**Issue by bilalhassanqadri** [ankesh-kumar/Flutter-chat#11]
i have tried to change the verion of   photo_view:  but it dose not support with the package please help thanks

/J:/flutter_windows_1.17.5-stable/flutter/.pub-cache/hosted/pub.dartlang.org/photo_view-0.11.1/lib/src/core/photo_view_gesture_detector.dart:106:29: Error: The argument type 'PointerEvent' can't be assigned to the parameter type 'PointerDownEvent'.
 - 'PointerEvent' is from 'package:flutter/src/gestures/events.dart' ('/J:/flutter_windows_1.17.5-stable/flutter/packages/flutter/lib/src/gestures/events.dart').
 - 'PointerDownEvent' is from 'package:flutter/src/gestures/events.dart' ('/J:/flutter_windows_1.17.5-stable/flutter/packages/flutter/lib/src/gestures/events.dart').
    super.addAllowedPointer(event);

**Comment by ankesh-kumar** [comment]
Must check compatibility of the flutter version and other plugins version, when you try to change any plugin version. Its not an issue.

**Comment by ankesh-kumar** [comment]
Must check compatibility of the flutter version and other plugins version, when you try to change any plugin version. Its not an issue.
