### ISSUE TITLE
Firebase config?

### ISSUE THREAD

**Issue by giorgio79** [ankesh-kumar/Flutter-chat#3]
I have just installed this project, and after tapping "just chat" I am getting

```
D/FirebaseAuth(22592): Notifying id token listeners about user ( XFGQ7Uqjh6bNyPweJoNKngU4CTt1 ).
W/RepoOperation(22592): setValue at /status/XFGQ7Uqjh6bNyPweJoNKngU4CTt1 failed: DatabaseError: Permission denied
E/flutter (22592): [ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: PlatformException(-3, Permission denied, )
```
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by giorgio79** [comment]
Ah, I just noticed I would need a Firebase Database, but I was using Cloud Firestore :) Will try to rewrite to use Cloud Firestore

**Comment by ankesh-kumar** [comment]
1. After installing the project, setup properly your project with Firebase (as already writteen in readme and make sense ), only then run it, it will not crash.

2. Repo using Cloud Firestore for chatting, just for checking user online status Firebase Database is using.
