### ISSUE TITLE
Firebase rules for security?

### ISSUE THREAD

**Issue by giorgio79** [ankesh-kumar/Flutter-chat#5]
How do you protect the Firebase table , so only auth users can access it?

I notice another project provided rules https://pub.dev/packages/flutter_firebase_chat_sdk

**Comment by giorgio79** [comment]
Tried sg like this, but getting perm denied
```
   match /messages/{userID1and2} { 
      //allow read: if request.auth != null;
      //allow write: if userID1and2.matches(request.auth.uid) == true;
      allow read, write: if true;

    }
```

**Comment by ankesh-kumar** [comment]
security rules added on readme
