### ISSUE TITLE
Flutter chat 

### ISSUE THREAD

**Issue by muhammednazil** [ankesh-kumar/Flutter-chat#8]
Can anyone show me how can I ingrate this chat with my app?
I need to remove the sign-in with google and automatically need to sign with my user and the documentation to do the things in cloud firestore.

Can any one can help me.

**Comment by muhammednazil** [comment]
I have two application to show the chat can you please give a proper guide way to do this.

**Comment by ankesh-kumar** [comment]
Hello, it is not an issue , it is feature request. 
By the way, You can use other authentication provided by firebase.(Anonymous authentication too).
